### ISSUE TITLE
Clarté de la démarche

### ISSUE THREAD

**Issue by welcomee** [sical/meta-education#13]
Vérifier si le calcul de cet indicateur prend en compte les ajouts et suppressions de liens (voir définition sur le ggdoc), ou il faut juste le rajouter sur le tooltip.

**Comment by clemsos** [comment]
Oui, il s'agit de la somme des actions "create" sur les actions "delete", donc pas différences entre nodes et liens
https://github.com/sical/meta-education/blob/master/app/src/routes/api.routes.js#L270
