### ISSUE TITLE
Calcul  indicateur "Liens par noeud"

### ISSUE THREAD

**Issue by welcomee** [sical/meta-education#15]
Selon le ggdoc, cet indicateur correspond à la moyenne des degré des nœuds qui conforment la carte mentale finale.
J'ai fait le calcul pour les élèves "40" et "17" regardant le graphe final et ayant comme résultats : 1,5 et 1,3 respectivement.
Peut-être il y a une erreur dans ces calculs ?
- Pour l'élève "40": (2liens + 1lien +2liens + 1lien) / 4noeuds = 1,5
- Pour l'élève "17": (1lien + 2liens + 1 lien) / 3 nœuds = 1,3

**Comment by clemsos** [comment]
Le calcul du degré moyen a lieu ici : https://github.com/sical/meta-education/blob/master/app/src/routes/api.routes.js#L280

**Comment by clemsos** [comment]
En fait, le degré est calculé pour les liens qui sont à al fois source & target, donc peut-être calculé deux fois ici. Il faut se mettre d'accord sur la façon dont on calcule le degré, puis faire la moyenne/

**Comment by clemsos** [comment]
Solution à intégrer ici : https://jsbin.com/zakolaseli/edit?js,console
